name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x', '6.0.x' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore SEP3_Solution/SEP3_Solution.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore SEP3_Solution/SEP3_Solution.sln

      - name: Run Tests
        run: |
          dotnet test SEP3_Solution/SEP3_Solution.sln --configuration Release --no-build --logger "trx;LogFileName=../Test/test_results.trx"
    
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: '**/test_results.json'
