name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 7.0.x

    - name: Build Broker
      run: dotnet build Broker/Broker.csproj
      working-directory: ./Broker

    - name: Test Broker
      run: dotnet test Broker/Broker.csproj
      working-directory: ./Broker
